FinalPtoject/Controllers/itemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalPtoject.Data;
using FinalPtoject.Models;
using Microsoft.Data.SqlClient;

namespace FinalPtoject.Controllers
{
    public class itemsController : Controller
    {
        private readonly FinalPtojectContext _context;

        public itemsController(FinalPtojectContext context)
        {
            _context = context;
        }


        //8
        public async Task<IActionResult> statis()
        {
            string ss = HttpContext.Session.GetString("Role");
            if (ss == "admin")
            {
                {
                    string sql = "";

                    var builder = WebApplication.CreateBuilder();
                    string conStr = builder.Configuration.GetConnectionString("FinalPtojectContext");
                    SqlConnection conn = new SqlConnection(conStr);

                    SqlCommand comm;
                    conn.Open();
                    sql = "SELECT COUNT( Id)  FROM items where category ='facep'";
                    comm = new SqlCommand(sql, conn);
                    ViewData["d1"] = (int)comm.ExecuteScalar();

                    sql = "SELECT COUNT( Id)  FROM items where category ='lipp'";
                    comm = new SqlCommand(sql, conn);
                    ViewData["d2"] = (int)comm.ExecuteScalar();

                    sql = "SELECT COUNT( Id)  FROM items ";
                    comm = new SqlCommand(sql, conn);
                    ViewData["totalItem"] = (int)comm.ExecuteScalar();
                    return View();
                }
            }
            else
                return RedirectToAction("login", "Usersalls");
        }


        //8

        public async Task<IActionResult> image_slider()
        {
            string ss = HttpContext.Session.GetString("Role");
            if (ss == "customer") 
                {
                    return _context.items != null ?
                            View(await _context.items.ToListAsync()) :
                            Problem("Entity set 'FinalPtojectContext.items'  is null.");
                }   else
                    return RedirectToAction("login", "Usersalls");
            } 




        //8
            public async Task<IActionResult> list()
        {
            string ss = HttpContext.Session.GetString("Role");
            if (ss == "customer")
            {
                return _context.items != null ?
                 View(await _context.items.OrderBy(m => m.category).ToListAsync()) :
                Problem("Entity set 'FinalPtojectContext.items'  is null.");
            }
            else
                return RedirectToAction("login", "Usersalls");
        }


        // GET: items
        public async Task<IActionResult> Index()
        {
            ViewData["role"] = HttpContext.Session.GetString("Role");

            return _context.items != null ?
                  View(await _context.items.ToListAsync()) :
                 Problem("Entity set 'FinalPtojectContext.items'  is null.");
        }

        // GET: items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.items == null)
            {
                return NotFound();
            }

            var items = await _context.items
                .FirstOrDefaultAsync(m => m.Id == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

     

        // GET: items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file,[Bind("Id,name,descr,price,quantity,discount,category")] items items)
        
            {
                if (file != null)
                {
                    string filename = file.FileName;
                    //  string  ext = Path.GetExtension(file.FileName);
                    string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                    using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                    { await file.CopyToAsync(filestream); }

                    items.imagefilename = filename;
                }

                _context.Add(items);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
        }

        // GET: items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.items == null)
            {
                return NotFound();
            }

            var items = await _context.items.FindAsync(id);
            if (items == null)
            {
                return NotFound();
            }
            return View(items);



        }

        // POST: items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, int id, [Bind("Id,name,descr,price,quantity,discount,category,imagefilename")] items items)
        {
     
            if (id != items.Id)
            { return NotFound(); }

            if (file != null)
            {
                string filename = file.FileName;
                //  string  ext = Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                items.imagefilename = filename;
            }
            _context.Update(items);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            return View(items);
        }

        // GET: items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.items == null)
            {
                return NotFound();
            }

            var items = await _context.items
                .FirstOrDefaultAsync(m => m.Id == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // POST: items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.items == null)
            {
                return Problem("Entity set 'FinalPtojectContext.items'  is null.");
            }
            var items = await _context.items.FindAsync(id);
            if (items != null)
            {
                _context.items.Remove(items);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool itemsExists(int id)
        {
          return (_context.items?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FinalPtoject/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalPtoject.Data;
using FinalPtoject.Models;
using Microsoft.Data.SqlClient;
using System.Composition;

namespace FinalPtoject.Controllers
{
    public class ordersController : Controller
    {
        private readonly FinalPtojectContext _context;

        public ordersController(FinalPtojectContext context)
        {
            _context = context;
        }

        // GET: orders
        public async Task<IActionResult> Index()
        {
            string ss = HttpContext.Session.GetString("Role");
            if (ss == "admin")
            {
                return _context.orders != null ?
                             View(await _context.orders.ToListAsync()) :
                             Problem("Entity set 'FinalPtojectContext.orders'  is null.");

            }
            else
                return RedirectToAction("login", "Usersalls");
        }



    //-
    public async Task<IActionResult> orderdetail(int? id)
        {
            var orItems = await _context.orderdetail.FromSqlRaw("SELECT orders.id as Id,usersall.name as username,items.name as itemname,orders.buydate as BuyDate,items.price * orders.quantity as TotalPrice ,orders.quantity as quantity FROM orders JOIN usersall ON orders.userid = usersall.id JOIN items ON orders.itemid = items.id Where orders.userid = '" + id + "' order by orders.buydate DESC").ToListAsync();
            return View(orItems);
        }


        
        public async Task<IActionResult> Report()
        {
            string ss = HttpContext.Session.GetString("Role");
            if (ss == "admin")
            {
                //   var orItems = await _context.report.FromSqlRaw("select userall.id as Id, userall.name as customername, sum(orders.quantity*items.price) as total, orders.buydate as Buydate from items, orders, userall where  itemid = items.Id and userid = userall.Id group by userall.id, userall.name,orders.buydate order by orders.buydate ").ToListAsync();
                // return View(orItems);
                List<Report> list = new List<Report>();

                var builder = WebApplication.CreateBuilder();
                string conStr = builder.Configuration.GetConnectionString("FinalPtojectContext");
                SqlConnection conn1 = new SqlConnection(conStr);
                string sql;
                sql = "select usersall.id as Id, usersall.name as customername, sum(orders.quantity*items.price) as total from items, orders, usersall where  itemid = items.Id and userid = usersall.Id group by usersall.id, usersall.name";
                SqlCommand comm = new SqlCommand(sql, conn1);
                conn1.Open();
                SqlDataReader reader = comm.ExecuteReader();
                while (reader.Read())
                {
                    list.Add(new Report
                    {
                        Id = (int)reader["Id"],
                        customername = (string)reader["customername"],
                        total = (int)reader["total"],

                    });
                }
                return View(list);

            }
            else
                return RedirectToAction("Login", "Usersalls");
        }


        //-
        public async Task<IActionResult> my_purchase()
        {
            string ss = HttpContext.Session.GetString("Role");
            if (ss == "customer")
            {
                int userid = (int)HttpContext.Session.GetInt32("userid");
                //var orItems = await _context.orders.FromSqlRaw("select *  from orders where  userid = '" + userid + "'  ").ToListAsync();

                List<my_purchase> list = new List<my_purchase>();

                var builder = WebApplication.CreateBuilder();
                string conStr = builder.Configuration.GetConnectionString("FinalPtojectContext");
                SqlConnection conn1 = new SqlConnection(conStr);
                string sql;
                sql = "SELECT usersall.id as Id,items.name as itemname,orders.Buydate as buydate,(items.price * orders.quantity) as Price ,orders.quantity as quantity FROM orders JOIN usersall ON orders.userid = usersall.id JOIN items ON orders.itemid = items.id Where orders.userid = '" + userid + "'";
                SqlCommand comm = new SqlCommand(sql, conn1);
                conn1.Open();
                SqlDataReader reader = comm.ExecuteReader();
                while (reader.Read())
                {
                    list.Add(new my_purchase
                    {
                        Id = (int)reader["Id"],
                        name = (string)reader["itemname"],
                        buydate = (DateTime)reader["buydate"],
                        price = (int)reader["Price"],
                        quantity = (int)reader["quantity"]
                    });
                }
                return View(list);

            }
            else
                return RedirectToAction("login", "Usersalls");
           

        }

        public async Task<IActionResult> Buy(int? id)
        {
            var item = await _context.items.FindAsync(id);
            return View(item);
        }
        [HttpPost]
        public async Task<IActionResult> Buy(int itemid, int quantity)
        {
            orders order = new orders();
            order.itemid = itemid;
            order.userid = (int)HttpContext.Session.GetInt32("userid");
            order.quantity = quantity;
            order.buydate = DateTime.Today;
            var builder = WebApplication.CreateBuilder();
            string conStr = builder.Configuration.GetConnectionString("FinalPtojectContext");
            SqlConnection conn = new SqlConnection(conStr);
            string sql;
            int qt = 0;
            sql = "select * from items where (id ='" + order.itemid + "' )";
            SqlCommand comm = new SqlCommand(sql, conn);
            conn.Open();
            SqlDataReader reader = comm.ExecuteReader();
            if (reader.Read())
            {
                qt = (int)reader["quantity"]; // store quantity
            }
            reader.Close();
            conn.Close();
            if (order.quantity > qt)
            {
                ViewData["message"] = "Maxiumam order quantity should be " + qt;
                var item = await _context.items.FindAsync(itemid);
                return View(item);
            }
            else
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                sql = "UPDATE items  SET quantity  = quantity   - '" + order.quantity + "'  where (id ='" + order.itemid + "' )";
                comm = new SqlCommand(sql, conn);
                conn.Open();
                comm.ExecuteNonQuery();
                conn.Close();
                return RedirectToAction(nameof(my_purchase));
            }
        }














        // GET: orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // GET: orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,itemid,userid,quantity,buydate")] orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            return View(orders);
        }

        // POST: orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,itemid,userid,quantity,buydate")] orders orders)
        {
            if (id != orders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ordersExists(orders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Report));
            }
            return View(orders);
        }

        // GET: orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.orders == null)
            {

FinalPtoject/Views/items/Create.cshtml
@model FinalPtoject.Models.items

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<hr />
<form asp-action="Create" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="name" class="control-label"></label>
        <input asp-for="name" class="form-control" />
        <span asp-validation-for="name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="descr" class="control-label"></label>
        <input asp-for="descr" class="form-control" />
        <span asp-validation-for="descr" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="price" class="control-label"></label>
        <input asp-for="price" class="form-control" />
        <span asp-validation-for="price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="quantity" class="control-label"></label>
        <input asp-for="quantity" class="form-control" />
        <span asp-validation-for="quantity" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="discount" class="control-label"></label>
        <div class="checkbox">
            <label> <input type="radio" asp-for="discount" value="yes" /> Yes</label>
        </div>
        <div class="checkbox">
            <label> <input type="radio" asp-for="discount" value="no" />No</label>
        </div>
        <span asp-validation-for="discount" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="control-label">Catagory</label>
        <select class="form-control" asp-for="category">
            <option value="selec">Please select</option>
            <option value="facep">Face Products</option>
            <option value="lipp">Lip Products</option>
        </select>
        <span asp-validation-for="category" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="control-label">Pic</label>
        <input type="file" class="form-control" name="file" />
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

FinalPtoject/Views/items/Delete.cshtml
@model FinalPtoject.Models.items

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>items</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imagefilename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imagefilename)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalPtoject/Views/items/Details.cshtml
@model FinalPtoject.Models.items

@{
    ViewData["Title"] = "Details";

}

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Details</h1>

<div>
    <h4>items</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.category)
        <dd>
            <img src="~/images/@Model.imagefilename" height="150" />
        </dd>
    </dl>
</div>

<div>
    <a asp-controller ="Usersalls" asp-action="customer_home">Back Home</a>
</div>

FinalPtoject/Views/items/Index.cshtml
@model IEnumerable<FinalPtoject.Models.items>

@{
    ViewData["Title"] = "Index";
}




<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
        body {
            background-color: antiquewhite;
        }
    </style>
</head>
 <body>
    @if ((string)ViewData["role"] == "customer")
    {

        Layout = "~/Views/Shared/_Layout1.cshtml";
    }



<h1>ItemManage</h1>
     @if ((string)ViewData["role"] == "admin") { 
           
    @await Html.PartialAsync("insertitems", new items())
    <br />
     }
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.discount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imagefilename)
            </th>
            <th> Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                
                
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.discount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
                <td>
                    <img src="~/images/@item.imagefilename" height="50" />
                    </td>
                <td>
               
                                @if ((string)ViewData["role"] == "admin")
                        {
                          //  <a asp-controller="items" asp-action="Edit" asp-route-id="@item.Id">Edit  |</a>
                            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="@("#editModal-" + @item.Id)">edit</button>
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="@("#deleteModal-" + @item.Id)">Delete</button>

                            @await Html.PartialAsync("deleteitems", item)
                            @await Html.PartialAsync("edititem", item)


                        }


                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="@("#detailModal-" + @item.Id)">Detail</button>
                        @await Html.PartialAsync("detailitem", item)
                    </td>


            </tr>
        }
    </tbody>
</table>
</body>

FinalPtoject/Views/items/image_slider.cshtml
@model IEnumerable<FinalPtoject.Models.items>

@{
    ViewData["Title"] = "Image_Slider";
}

<h1>Products Images</h1>

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            background-color: antiquewhite;
        }
    </style>



</head>

<div id="myCarousel" style="width:30% ; min-width:300px " class="carousel slide mx-auto" data-ride="carousel">
    <div class="carousel-inner" id="demo">
        @{
            var counter = 0;
        }
        @foreach (var item in Model)
        {
            <div class='carousel-item   @(counter == 0 ? "active"  : String.Empty)'>

                <center> <img src="~/images/@item.imagefilename" height="400"> </center>

                <div class='carousel-caption mx-auto' style='top:77%; left:15%;'>
                    <h3 style='width:150px' class='mx-auto bg-secondary  text-white'>  @item.price SR  </h3>
                    <h6 style='width:150px' class='mx-auto bg-light  text-white'>  <a asp-controller="orders" asp-action="Buy" asp-route-id="@item.Id">Buy!</a>  </h6>

                </div>
            </div>
            counter++;
        }
    </div>
    <a class="carousel-control-prev " href="#myCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon bg-secondary"></span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" data-slide="next">
        <span class="carousel-control-next-icon bg-secondary"></span>
    </a>
</div>

FinalPtoject/Views/items/list.cshtml
@model IEnumerable<FinalPtoject.Models.items>
@{
    ViewData["Title"] = "list";
}
@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>list</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
         
        
        </tr>
}
    </tbody>
</table>